config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :tasks do
    resources :comments do
      patch :approve, on: :member
      patch :reject, on: :member
    end
  end

  # get 'tasks/:task_id/comments/new', to: 'comments#new', as: :new_task_comment

  root to: 'tasks#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :task

  has_one_attached :image

  validates :body, presence: true

  def thumbnail
    image.variant(resize_to_limit: [600, 600])
  end

end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :user, optional: true

  has_many :comments, dependent: :destroy

  private

  def set_default_values
    self.your_field ||= 'default_value'
  end
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :tasks, dependent: :destroy

  has_many :comments, dependent: :destroy

  def admin?
    role == 'admin'
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    def after_sign_out_path_for(resource_or_scope)
      new_user_session_path
    end
  end
  

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_task
  before_action :set_comment, only: [:edit, :update, :destroy]

  def new
    if @task.comments.where(user_id: current_user.id).exists?
      flash[:alert] = "You have already commented on this task."
      redirect_to task_path(@task)
    else
      @comment = @task.comments.new
    end
  end

  def show
    @comment = Comment.new
    @comments = current_user.admin? ? @task.comments.includes(:user) : @task.comments.where(user: current_user).includes(:user)
  end
  

  def create
    @comment = @task.comments.build(comment_params)
    @comment.user = current_user

    if @task.comments.where(user_id: current_user.id).exists?
      flash[:alert] = "You can only add one comment per task."
      redirect_to task_path(@task)
    elsif @comment.save
      flash[:notice] = "Comment added successfully."
      redirect_to task_path(@task)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @comment = @task.comments.find(params[:id])
  end

  def update
    if @comment.update(comment_params)
      flash[:notice] = "Comment updated successfully."
      redirect_to task_path(@task)
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @comment.destroy
    flash[:notice] = "Comment deleted successfully."
    redirect_to task_path(@task)
  end


  def approve
    @comment = @task.comments.find_by(id: params[:id])
    
    if @comment
      @comment.update(status: 'approved')
      redirect_to @task, notice: 'Comment approved.'
    else
      redirect_to @task, alert: 'Comment not found.'
    end
  end
  
  def reject
    @comment = @task.comments.find_by(id: params[:id])
    
    if @comment
      @comment.update(status: 'rejected')
      redirect_to @task, notice: 'Comment rejected.'
    else
      redirect_to @task, alert: 'Comment not found.'
    end
  end

  

  private

  def set_comment
    @comment = @task.comments.find(params[:id])
  end

  def set_task
    @task = Task.find(params[:task_id])
  end

  def comment_params
    params.require(:comment).permit(:body, :image)
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
    before_action :authenticate_user!
    before_action :set_task, only: %i[edit update destroy show]
  
    def index
      if current_user.admin?
        @tasks = Task.all
        @users = User.where.not(id: current_user.id)
      else
        @tasks = current_user.tasks
      end
    end

    def show
      @task = Task.find(params[:id])
      @comments = @task.comments.includes(:user)
      @comment = current_user.comments.find_or_initialize_by(task: @task) if current_user == @task.user
    end       
  
    def new
      @task = Task.new
    end
  
    def create
      @task = Task.new(task_params)
      @task.priority = 'low'
      
      if @task.save
        redirect_to tasks_path, notice: "Task was successfully created."
      else
        render :new
      end
    end
  
    def edit
    end


    def update
      if task_params[:user_id]
        @task.comments.destroy_all if task_params[:user_id] && task_params[:user_id] != @task.user_id
        @task.status = 'pending'
      end

      if @task.update(task_params)
        redirect_to tasks_path, notice: "Task #{@task.title} was successfully updated."
      else
        render :edit
      end
    end
  
    def destroy
      @task.destroy
      redirect_to tasks_path, notice: "#{@task.title} was successfully deleted."
    end
  
    private
  
    def set_task
      @task = Task.find(params[:id])
    end
  
    def task_params
      params.require(:task).permit(:title, :description, :status, :user_id, :priority)
    end
  end
  

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/comments/_form.html.erb
<%= form_with(model: [@task, @comment], local: true, html: { multipart: true }) do |form| %>
  <div class="mb-4">
    <%= form.label :body, class: 'block text-gray-700' %>
    <%= form.text_area :body, class: "w-full mt-1 p-2 border border-gray-300 rounded-md", placeholder: "Write a comment..." %>
  </div>

  <div class="mb-4">
    <%= form.label :image, class: "block text-gray-700 text-sm font-bold mb-2"  %>
    <%= form.file_field :image, class: "shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline" %>
  </div>
  
  <%= form.submit 'Add Comment', class: "bg-gray-400 hover:bg-gray-300 text-white font-bold py-2 px-4 rounded" %>
<% end %>

app/views/comments/edit.html.erb
<h1>Edit Comment</h1>

<%= render partial: 'form', locals: { comment: @comment } %>

<%= link_to 'Back to Task', task_path(@task), class: "text-blue-500 hover:underline mt-4 block" %>

app/views/comments/new.html.erb
<h1 class="text-2xl font-bold mb-4">Add a Comment</h1>

<%= render partial: 'form', locals: { task: @task, comment: Comment.new } %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Taskify</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload", "media": "all" %>
    <meta name="turbo-prefetch" content="false">
    <%= javascript_importmap_tags %>
  </head>

  <body class="bg-gray-100 text-gray-900">
    <nav class="bg-white shadow-md p-4">
      <% flash.each do |key, message| %>
        <div class="alert alert-<%= key %>">
          <%= message %>
        </div>
      <% end %>
      <div class="container mx-auto flex justify-between items-center">
        <div class="flex items-center space-x-4">
          <% if user_signed_in? %>
            <%= link_to 'Home', root_path, class: "text-white font-bold bg-gray-400 border border-gray-400 rounded-md px-4 py-2 hover:bg-gray-300 transition duration-300 rounded" %>
          <% end %>
        </div>
        <div class="flex items-center space-x-4">
          <% if user_signed_in? %>
            <%= link_to 'Edit Profile', edit_user_registration_path, class: "text-white font-bold bg-gray-400 border border-gray-300 rounded-md px-4 py-2 hover:bg-gray-300 transition duration-300 rounded" %>
            <%= button_to 'Sign Out', destroy_user_session_path, method: :delete, class: "text-white font-bold bg-gray-400 border border-gray-300 rounded-md px-4 py-2 hover:bg-gray-300 transition duration-300 rounded" %>
          <% else %>
            <%= link_to 'Sign In', new_user_session_path, class: " text-white font-bold bg-gray-400 border border-gray-300 rounded-md px-4 py-2 hover:bg-gray-300 transition duration-300 rounded" %>
            <%= link_to 'Sign Up', new_user_registration_path, class: "text-white font-bold bg-gray-400 border border-gray-300 rounded-md px-4 py-2 hover:bg-gray-300 transition duration-300 rounded" %>
          <% end %>
        </div>
      </div>
    </nav>

    <div class="container mx-auto mt-8">
      <%= yield %>
    </div>
  </body>
</html>

app/views/tasks/_form.html.erb
<%= form_with(model: @task, local: true) do |form| %>
  <div class="mb-4">
    <%= form.label :title, class: "block text-gray-700 text-sm font-bold mb-2" %>
    <%= form.text_field :title, class: "shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline" %>
  </div>

  <div class="mb-4">
    <%= form.label :description, class: "block text-gray-700 text-sm font-bold mb-2" %>
    <%= form.text_area :description, class: "shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline" %>
  </div>

  <div class="mb-4">
    <%= form.label :user_id, "Assign to", class: "block text-gray-700 text-sm font-bold mb-2" %>
    <%= form.collection_select :user_id, User.where.not(id: current_user.id), :id, :email, prompt: "Select a user", class: "shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline" %>
  </div>

  <div class="mb-4">
    <%= form.submit submit_text, class: "bg-gray-400 hover:bg-gray-300 text-white font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline" %>
  </div>
<% end %>

app/views/tasks/edit.html.erb
<h1 class="text-2xl font-bold mb-4">Edit Task</h1>

<%= render 'form', task: @task, submit_text: 'Update Task' %>

app/views/tasks/index.html.erb
<% if current_user.admin? %>
<h1 class="text-2xl inline bg-indigo-50 font-bold italic text-red-500 mb-4">Admin Profile</h1>
  <div class="flex justify-between items-center mb-4">
    <h1 class="text-2xl font-bold mb-4">All Tasks</h1>
    <%= link_to 'New Task', new_task_path, class: 'bg-blue-500 text-white font-bold py-2 px-4 rounded-md hover:bg-blue-700 transition duration-300' %>
  </div>

  <table class="min-w-full divide-y divide-gray-200">
    <thead>
      <tr>
        <th>Title</th>
        <th>Description</th>
        <th>Status</th>
        <th>User</th>
        <th>Priority</th>
        <th>Actions</th>
      </tr>
    </thead>
    <tbody class="min-w-full bg-white divide-y divide-gray-200">
      <% @tasks.each do |task| %>
        <tr>
          <td><%= task.title %></td>
          <td><%= task.description %></td>
          <td><%= task.status %></td>
          <td><%= task.user.present? ? task.user.email : 'Unassigned' %></td>
          <td><%= task.priority%></td>
          <td>
            <%= link_to 'Edit', edit_task_path(task), class: 'text-blue-500 hover:underline' %> |
            <%= link_to 'Show', task_path(task), class: 'text-blue-500 hover:underline' %>
          </td>
          <td>
            <%= button_to 'Delete', task, method: :delete, data: { confirm: 'Are you sure?' }, class: 'text-red-500 hover:underline' %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <h2 class="text-2xl font-bold mt-8">Users</h2>
  <ul>
    <% @users.each do |user| %>
      <li class="min-w-full bg-white divide-y divide-gray-200"><%= user.email %> - <%= user.role %></li>
    <% end %>
  </ul>

<% else %>
  <h1 class="text-2xl font-bold mb-4">My Tasks</h1>
  <table class="min-w-full bg-white divide-y divide-gray-200">
    <thead>
      <tr>
        <th>Title</th>
        <th>Description</th>
        <th>Status</th>
        <th>Actions</th>
        <th>Comments</th> 
      </tr>
    </thead>
    <tbody class="min-w-full bg-white divide-y divide-gray-200">
      <% @tasks.each do |task| %>
        <tr>
          <td><%= task.title %></td>
          <td><%= task.description %></td>
          <td><%= task.status %></td>
          <td>
            <%= button_to 'Mark as Complete', task_path(task, task: { status: 'complete' }), method: :patch, class: 'text-green-500 hover:underline' if task.status == 'pending' %>
            <%= button_to 'Mark as Pending', task_path(task, task: { status: 'pending' }), method: :patch, class: 'text-yellow-500 hover:underline' if task.status == 'complete' %>
          </td>
          <td>
          <% user_comment = task.comments.find_by(user_id: current_user.id) %>

          <% if user_comment.present? %>
             <%= link_to 'Show Comment', task_path(task), class: 'text-blue-500 hover:underline' %>
          </td>
          <% else %>
            <%= link_to 'Add Comment', task_path(task), class: 'text-blue-500 hover:underline' %>
          <% end %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% end %>

app/views/tasks/new.html.erb
<h1 class="text-2xl font-bold mb-4">New Task</h1>

<%= render 'form', task: @task, submit_text: 'Create Task' %>

app/views/tasks/show.html.erb
<h1 class="text-2xl font-bold mb-4">Task Details</h1>

<p><strong>Title:</strong> <%= @task.title %></p>
<p><strong>Description:</strong> <%= @task.description %></p>
<p><strong>Status:</strong> <%= @task.status %></p>
<p><strong>Assigned to:</strong> <%= @task.user.present? ? @task.user.email : 'Unassigned' %></p>

<div class="mt-4">
  <%= link_to 'Edit Task', edit_task_path(@task), class: 'text-blue-500 hover:underline' %>
  <%= link_to 'Back to Tasks', tasks_path, class: 'text-blue-500 hover:underline ml-4' %>
</div>


  <h2 class="text-xl font-bold mt-8">Comments</h2>
  <ul class="mt-4">
    <% if @task.comments.any? %>
      <% @task.comments.each do |comment| %>
        <li class="mb-2 p-4 bg-gray-100 rounded-md shadow-md">
          <strong><%= comment.user.email %>:</strong>
          <p><strong>Status:</strong> <%= comment.status.presence || "" %></p>
          <p class="mt-1"><strong>Comment:</strong> <%= comment.body.presence || "No comment" %></p>
          <% if comment.image.attached? %>
          <%= image_tag comment.thumbnail, class: "mt-2 max-w-full h-auto" %>
        <% end %>
          <div class="mt-2 flex items-center space-x-2"> 
          <% if current_user.admin? %>    
          
            <%= button_to 'Approve', approve_task_comment_path(@task, comment), method: :patch, class: "bg-gray-400 text-white font-bold py-2 px-4 rounded hover:bg-green-300" %>     
            <%= button_to 'Reject', reject_task_comment_path(@task, comment), method: :patch, class: "bg-gray-400 text-white font-bold py-2 px-4 rounded hover:bg-pink-300" %>      
 
            <%= button_to 'Delete', task_comment_path(@task, comment), method: :delete, data: { confirm: 'Are you sure?' }, class: "text-white font-bold bg-gray-400 border border-gray-300 rounded-md px-4 py-2 hover:bg-gray-300 rounded" %>
            <% else %>

            <% if comment.status.present? %>
            <p><strong>Your comment has been <%= comment.status %> by the admin</strong></p>
            <% else %>
            <%= link_to 'Edit', edit_task_comment_path(@task, comment), class: 'text-white font-bold bg-gray-400 border border-gray-300 rounded-md px-4 py-2 hover:bg-gray-300 rounded' %>
            <%= button_to 'Delete', task_comment_path(@task, comment), method: :delete, data: { confirm: 'Are you sure?' }, class: 'text-white font-bold bg-gray-400 border border-gray-300 rounded-md px-4 py-2 hover:bg-gray-300 rounded' %>
            <% end %>
            <% end %>
          
            </div>
        </li>
      <% end %>
    <% else %>
    <% if current_user.admin? %>
    <p>No comments available for this task.</p>
    <% else %>
    <%= render partial: 'comments/form', locals: { task: @task } %>
    <% end %>
    <% end %>
  </ul>